### ISSUE TITLE
seriously?

### ISSUE THREAD

**Issue by sangeeth96** [mstcvit/portaltohack#5]
🙄

**Comment by sangeeth96** [comment]
@prkhandelwal 🤦‍♂️

**Comment by sangeeth96** [comment]
Arey, make some contributions. It can be docs if you don't want to code. Please don't do this. 🙏

**Comment by sangeeth96** [comment]
A puppy dies for every unethical PR made during HF.

**Comment by tannmaysgupta** [comment]
Lol I was excited for hacktober fest
Can close it now though
